version: "3"
services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
    container_name: nginx
    volumes:
      - wp-pages:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart:
      always
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - WP_DATABASE_HOST
        - DOMAIN_NAME
        - WP_DATABASE_NAME
        - WP_DATABASE_USER
        - WP_DATABASE_PASSWORD
        - WP_URL
        - WP_TITLE
        - WP_ADMIN_USER
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASSWORD
        - WP_USER_EMAIL
    env_file:
      - .env
    container_name: wordpress
    volumes:
      - wp-pages:/var/www/wordpress
    networks:
      - inception
    restart:
      always
    depends_on:
      - mariadb
      - redis
  
  redis:
    image: redis
    build:
      context: ./bonus/redis
    container_name: redis
    networks:
      - inception
    restart:
      always

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - WP_DATABASE_NAME
        - WP_DATABASE_USER
        - WP_DATABASE_PASSWORD
        - WP_DATABASE_ROOT
        - WP_DATABASE_ROOT_PASSWORD
    container_name: mariadb
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - inception
    restart:
      always

volumes:
  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/wp-database'
  wp-pages:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/wp-pages'

networks:
  inception:
    driver: bridge
    name: inception
