version: "3"
services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
    container_name: nginx
    volumes:
      - wp-pages:/var/www/wordpress
      - adminer-volume:/var/www/adminer
    ports:
      - "443:443"
    networks:
      - inception
    restart:
      always
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - WP_DATABASE_HOST
        - DOMAIN_NAME
        - WP_DATABASE_NAME
        - WP_DATABASE_USER
        - WP_DATABASE_PASSWORD
        - WP_URL
        - WP_TITLE
        - WP_ADMIN_USER
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASSWORD
        - WP_USER_EMAIL
        - REDIS_HOST
        - REDIS_PORT
    env_file:
      - .env
    container_name: wordpress
    volumes:
      - wp-pages:/var/www/wordpress
    networks:
      - inception
    restart:
      always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - WP_DATABASE_NAME
        - WP_DATABASE_USER
        - WP_DATABASE_PASSWORD
        - WP_DATABASE_ROOT
        - WP_DATABASE_ROOT_PASSWORD
    container_name: mariadb
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - inception
    restart:
      always

  adminer:
    image: adminer
    build:
      context: ./bonus/adminer
    container_name: adminer
    volumes:
      - adminer-volume:/var/www/adminer
    networks:
      - inception
    restart:
      always
    depends_on:
      - mariadb
  
  ftp:
    image: ftp
    build:
      context: ./bonus/ftp
      args:
        - FTP_PATH
        - FTP_USER
        - FTP_PASSWORD
    container_name: ftp
    volumes:
      - wp-pages:/var/www/wordpress
    networks:
      - inception
    ports:
      - "21:21"
      - "10090-10100:10090-10100"
    restart:
      always
    depends_on:
      - wordpress
  
  redis:
    image: redis
    build:
      context: ./bonus/redis
    container_name: redis
    networks:
      - inception
    restart:
      always
    depends_on:
      - wordpress

  site:
    image: site
    build:
      context: ./bonus/site
    container_name: site
    networks:
      - inception
    restart:
      always

  cadvisor:
    image: cadvisor
    build:
      context: ./bonus/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - inception
    restart:
      always

  minecraft:
    image: minecraft
    build:
      context: ./bonus/minecraft
    container_name: minecraft
    volumes:
      - minecraft-volume:/minecraft
    ports:
      - "25565:25565"
    networks:
      - inception
    restart:
      always

volumes:
  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/wp-database'
  wp-pages:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/wp-pages'
  adminer-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/adminer-volume'
  minecraft-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/etachott/data/minecraft-volume'

networks:
  inception:
    driver: bridge
    name: inception
